# Generated by Django 4.1 on 2022-08-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
                ('amount', models.IntegerField()),
                ('city', models.TextField(max_length=40)),
                ('comment', models.TextField(max_length=200)),
            ],
        ),
    ]
