# Generated by Django 4.1 on 2022-08-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(blank=True, choices=[('North', 'N'), ('South', 'S'), ('Center', 'c')], max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='cur_to_get',
            field=models.CharField(blank=True, choices=[('shekel', 'shekel'), ('dollar', 'dollar')], max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='cur_to_give',
            field=models.CharField(blank=True, choices=[('shekel', 'shekel'), ('dollar', 'dollar')], max_length=20),
        ),
    ]
