# Generated by Django 4.1 on 2022-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_area_post_cur_to_get_post_cur_to_give'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.CharField(blank=True, choices=[('North', 'North'), ('South', 'South'), ('Center', 'Center')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='cur_to_get',
            field=models.CharField(blank=True, choices=[('shekel', '₪'), ('dollar', '$')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='cur_to_give',
            field=models.CharField(blank=True, choices=[('shekel', '₪'), ('dollar', '$')], max_length=20),
        ),
    ]
