# Generated by Django 4.1 on 2022-09-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_phone_number_alter_post_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.TextField(default='admin', max_length=40),
        ),
    ]
