# Generated by Django 3.2.4 on 2022-11-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221112_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.CharField(max_length=20),
        ),
    ]
