# Generated by Django 3.2.4 on 2022-12-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_post_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='admin', max_length=40)),
                ('name', models.TextField(max_length=20)),
                ('phone_number', models.TextField(blank=True, default=None, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('my_offer', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('city', models.TextField(max_length=40)),
                ('comment', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('created_date', models.DateField()),
            ],
        ),
    ]
